# Generated by Django 5.2.7 on 2025-10-28 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InformacionBasica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.CharField(max_length=200, verbose_name='Perfil Profesional')),
                ('area_conocimiento', models.CharField(max_length=200, verbose_name='Área de Conocimiento')),
                ('tipo_perfil', models.CharField(max_length=200, verbose_name='Tipo de Perfil')),
                ('profesion', models.CharField(max_length=200, verbose_name='Profesión')),
                ('experiencia', models.CharField(max_length=200, verbose_name='Tipo de Experiencia')),
                ('tiempo_experiencia', models.CharField(max_length=200, verbose_name='Tiempo de Experiencia')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='Cédula')),
                ('descripcion', models.TextField(verbose_name='Descripción del Cargo')),
                ('genero', models.CharField(max_length=50, verbose_name='Género')),
                ('base_anexo_11', models.CharField(max_length=200, verbose_name='Base Anexo 11')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
        ),
        migrations.CreateModel(
            name='InformacionAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_expedicion', models.DateField(verbose_name='Fecha de Expedición Tarjeta Profesional')),
                ('tarjeta_profesional', models.CharField(max_length=100, verbose_name='Tarjeta o Resolución Profesional')),
                ('profesion', models.CharField(max_length=200, verbose_name='Profesión')),
                ('universidad', models.CharField(max_length=200, verbose_name='Universidad')),
                ('numero_tarjeta_resolucion', models.CharField(max_length=100, verbose_name='N° Tarjeta o Resolución')),
                ('fecha_grado', models.DateField(verbose_name='Fecha de Grado')),
                ('meses_experiencia_profesion', models.IntegerField(verbose_name='Meses de Experiencia por Profesión')),
                ('informacion_basica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formacion_academica', to='formapp.informacionbasica')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificado_laboral', models.FileField(upload_to='certificados_laborales/', verbose_name='Certificado Laboral o Contractual')),
                ('meses_experiencia', models.IntegerField(verbose_name='Meses de Experiencia')),
                ('dias_experiencia', models.IntegerField(verbose_name='Días de Experiencia')),
                ('dias_residual_experiencia', models.IntegerField(verbose_name='Días Residuales de Experiencia')),
                ('cargo', models.CharField(max_length=200, verbose_name='Cargo')),
                ('cargo_anexo_11', models.CharField(max_length=200, verbose_name='Cargo Anexo 11')),
                ('objeto_contractual', models.TextField(verbose_name='Objeto Contractual')),
                ('funciones', models.TextField(verbose_name='Funciones')),
                ('fecha_inicial', models.DateField(verbose_name='Fecha Inicial')),
                ('fecha_terminacion', models.DateField(verbose_name='Fecha de Terminación')),
                ('informacion_basica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias_laborales', to='formapp.informacionbasica')),
            ],
        ),
        migrations.CreateModel(
            name='CalculoExperiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_meses_experiencia', models.IntegerField(verbose_name='Total Meses Experiencia Certificada')),
                ('total_dias_experiencia', models.IntegerField(verbose_name='Total Días Experiencia Certificada')),
                ('total_dias_residual_experiencia', models.IntegerField(verbose_name='Total Días Residuales Experiencia Certificada')),
                ('total_experiencia_anos', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Total Experiencia en Años')),
                ('anos_y_meses_experiencia', models.CharField(max_length=100, verbose_name='Años y Meses de Experiencia')),
                ('informacion_basica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calculo_experiencia', to='formapp.informacionbasica')),
            ],
        ),
        migrations.CreateModel(
            name='Posgrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_posgrado', models.CharField(max_length=200, verbose_name='Nombre del Posgrado')),
                ('universidad', models.CharField(max_length=200, verbose_name='Universidad')),
                ('fecha_terminacion', models.DateField(verbose_name='Fecha de Terminación')),
                ('informacion_basica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posgrados', to='formapp.informacionbasica')),
            ],
        ),
    ]
