# Generated by Django 5.2.7 on 2025-10-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0002_informacionbasica_nombre_completo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informacionbasica',
            name='direccion',
        ),
        migrations.AddField(
            model_name='informacionbasica',
            name='barrio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Barrio'),
        ),
        migrations.AddField(
            model_name='informacionbasica',
            name='complemento_direccion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento (Apto, Interior, etc.)'),
        ),
        migrations.AddField(
            model_name='informacionbasica',
            name='numero_casa',
            field=models.CharField(default='', max_length=20, verbose_name='Número de Casa/Edificio'),
        ),
        migrations.AddField(
            model_name='informacionbasica',
            name='numero_via',
            field=models.CharField(default='', max_length=20, verbose_name='Número de Vía'),
        ),
        migrations.AddField(
            model_name='informacionbasica',
            name='tipo_via',
            field=models.CharField(default='Calle', max_length=50, verbose_name='Tipo de Vía (Calle/Avenida/Carrera)'),
        ),
        migrations.AlterField(
            model_name='informacionbasica',
            name='genero',
            field=models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino')], max_length=50, verbose_name='Género'),
        ),
    ]
