# Generated by Django 5.2.7 on 2025-10-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0003_remove_informacionbasica_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacionbasica',
            name='area_del_conocimiento',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Área del Conocimiento'),
        ),
        migrations.AlterField(
            model_name='informacionacademica',
            name='fecha_expedicion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Expedición'),
        ),
        migrations.AlterField(
            model_name='informacionacademica',
            name='meses_experiencia_profesion',
            field=models.IntegerField(default=0, verbose_name='Meses de Experiencia por Profesión'),
        ),
        migrations.AlterField(
            model_name='informacionacademica',
            name='numero_tarjeta_resolucion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='N° Tarjeta o Resolución'),
        ),
        migrations.AlterField(
            model_name='informacionacademica',
            name='tarjeta_profesional',
            field=models.CharField(choices=[('Tarjeta Profesional', 'Tarjeta Profesional'), ('Resolución', 'Resolución'), ('No Aplica', 'No Aplica')], default='No Aplica', max_length=100, verbose_name='Tarjeta o Resolución Profesional'),
        ),
    ]
