# Generated by Django 5.2.7 on 2025-10-29 15:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0004_informacionbasica_area_del_conocimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posgrado',
            name='meses_de_experiencia',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
