# Generated by Django 5.2.7 on 2025-10-29 16:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0005_posgrado_meses_de_experiencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posgrado',
            name='meses_de_experiencia',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Meses de Experiencia'),
        ),
    ]
