# Generated by Django 5.2.7 on 2025-10-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0006_alter_posgrado_meses_de_experiencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacionbasica',
            name='area_conocimiento',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Área de Conocimiento'),
        ),
        migrations.AlterField(
            model_name='informacionbasica',
            name='base_anexo_11',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Base Anexo 11'),
        ),
        migrations.AlterField(
            model_name='informacionbasica',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='informacionbasica',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción del Cargo'),
        ),
        migrations.AlterField(
            model_name='informacionbasica',
            name='experiencia',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tipo de Experiencia'),
        ),
        migrations.AlterField(
            model_name='informacionbasica',
            name='perfil',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Perfil Profesional'),
        ),
        migrations.AlterField(
            model_name='informacionbasica',
            name='profesion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Profesión'),
        ),
        migrations.AlterField(
            model_name='informacionbasica',
            name='tiempo_experiencia',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tiempo de Experiencia'),
        ),
        migrations.AlterField(
            model_name='informacionbasica',
            name='tipo_perfil',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tipo de Perfil'),
        ),
    ]
