# Generated by Django 5.2.7 on 2025-10-29 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0007_alter_informacionbasica_area_conocimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculoexperiencia',
            name='total_dias_residual_experiencia',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='dias_residual_experiencia',
        ),
    ]
