# Generated by Django 5.2.7 on 2025-10-30 21:06

import formapp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0008_remove_calculoexperiencia_total_dias_residual_experiencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencialaboral',
            name='certificado_laboral',
            field=models.FileField(help_text='Formatos permitidos: PDF, JPG, PNG. Tamaño máximo: 10 MB', upload_to='certificados_laborales/', validators=[formapp.validators.validate_file_size, formapp.validators.validate_file_extension], verbose_name='Certificado Laboral o Contractual'),
        ),
        migrations.AlterField(
            model_name='informacionbasica',
            name='cedula',
            field=models.CharField(error_messages={'unique': 'Ya existe un registro con esta cédula. Por favor, verifica el número de cédula.'}, max_length=20, unique=True, verbose_name='Cédula'),
        ),
    ]
