# Generated by Django 5.2.7 on 2025-11-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0009_alter_experiencialaboral_certificado_laboral_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informacionbasica',
            name='base_anexo_11',
        ),
        migrations.RemoveField(
            model_name='informacionbasica',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='informacionbasica',
            name='contrato',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Contrato'),
        ),
        migrations.AddField(
            model_name='informacionbasica',
            name='organizacion',
            field=models.TextField(blank=True, null=True, verbose_name='Organización'),
        ),
    ]
