# Generated by Django 5.2.7 on 2025-11-05 13:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0010_remove_informacionbasica_base_anexo_11_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especializacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_especializacion', models.CharField(max_length=200, verbose_name='Nombre de la Especialización')),
                ('universidad', models.CharField(max_length=200, verbose_name='Universidad')),
                ('fecha_terminacion', models.DateField(verbose_name='Fecha de Terminación')),
                ('meses_de_experiencia', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Meses de Experiencia')),
                ('informacion_basica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especializaciones', to='formapp.informacionbasica')),
            ],
        ),
    ]
