# Generated by Django 5.2.7 on 2025-11-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0011_especializacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencialaboral',
            name='cargo_anexo_11',
            field=models.CharField(blank=True, default='Profesional', max_length=200, verbose_name='Cargo Anexo 11'),
        ),
    ]
