# Generated by Django 5.2.7 on 2025-11-05 20:00

import formapp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0012_alter_experiencialaboral_cargo_anexo_11'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencialaboral',
            name='certificado_laboral',
            field=models.FileField(help_text='Formatos permitidos: PDF, JPG, PNG. Tamaño máximo: 10 MB', upload_to='certificados_laborales/', validators=[formapp.validators.validate_file_size, formapp.validators.validate_file_extension, formapp.validators.validate_file_mime], verbose_name='Certificado Laboral o Contractual'),
        ),
    ]
