# Generated by Django 5.2.7 on 2025-11-19 00:53

import django.db.models.deletion
import formapp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0013_alter_experiencialaboral_certificado_laboral'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentosIdentidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotocopia_cedula', models.FileField(help_text='Formatos permitidos: PDF, JPG, PNG. Tamaño máximo: 10 MB', upload_to='documentos_identidad/cedulas/', validators=[formapp.validators.validate_file_size, formapp.validators.validate_file_extension, formapp.validators.validate_file_mime], verbose_name='Fotocopia Cédula de Ciudadanía')),
                ('libreta_militar', models.FileField(blank=True, help_text='Requerido para hombres. Formatos: PDF, JPG, PNG. Máx: 10 MB', null=True, upload_to='documentos_identidad/libretas_militares/', validators=[formapp.validators.validate_file_size, formapp.validators.validate_file_extension, formapp.validators.validate_file_mime], verbose_name='Libreta Militar')),
                ('numero_libreta_militar', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Libreta Militar')),
                ('distrito_militar', models.CharField(blank=True, max_length=100, null=True, verbose_name='Distrito Militar')),
                ('clase_libreta', models.CharField(blank=True, choices=[('Primera', 'Primera Clase'), ('Segunda', 'Segunda Clase')], max_length=50, null=True, verbose_name='Clase de Libreta')),
                ('carta_autorizacion_datos', models.FileField(help_text='Autorización según Ley 1581 de 2012. Formatos: PDF, JPG, PNG. Máx: 10 MB', upload_to='autorizaciones/', validators=[formapp.validators.validate_file_size, formapp.validators.validate_file_extension, formapp.validators.validate_file_mime], verbose_name='Carta de Autorización Tratamiento de Datos')),
                ('fecha_autorizacion', models.DateField(verbose_name='Fecha de Autorización')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('informacion_basica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_identidad', to='formapp.informacionbasica')),
            ],
            options={
                'verbose_name': 'Documentos de Identidad',
                'verbose_name_plural': 'Documentos de Identidad',
            },
        ),
    ]
