# Generated by Django 5.2.7 on 2025-11-19 00:59

import formapp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0014_documentos_identidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacionacademica',
            name='certificado_vigencia_tarjeta',
            field=models.FileField(blank=True, help_text='Certificado de vigencia de tarjeta profesional. Formatos: PDF, JPG, PNG. Máx: 10 MB', null=True, upload_to='certificados_vigencia/', validators=[formapp.validators.validate_file_size, formapp.validators.validate_file_extension, formapp.validators.validate_file_mime], verbose_name='Certificado de Vigencia'),
        ),
        migrations.AddField(
            model_name='informacionacademica',
            name='fecha_vigencia_tarjeta',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Vigencia del Certificado'),
        ),
        migrations.AddField(
            model_name='informacionacademica',
            name='fotocopia_tarjeta_profesional',
            field=models.FileField(blank=True, help_text='Solo si aplica. Formatos: PDF, JPG, PNG. Máx: 10 MB', null=True, upload_to='tarjetas_profesionales/', validators=[formapp.validators.validate_file_size, formapp.validators.validate_file_extension, formapp.validators.validate_file_mime], verbose_name='Fotocopia Tarjeta Profesional'),
        ),
        migrations.AddField(
            model_name='informacionacademica',
            name='fotocopia_titulo',
            field=models.FileField(blank=True, help_text='Acta de grado o diploma. Formatos: PDF, JPG, PNG. Máx: 10 MB', null=True, upload_to='titulos_academicos/', validators=[formapp.validators.validate_file_size, formapp.validators.validate_file_extension, formapp.validators.validate_file_mime], verbose_name='Fotocopia del Título/Diploma'),
        ),
    ]
