# Generated by Django 5.2.7 on 2025-11-19 01:01

import django.db.models.deletion
import formapp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0015_documentos_academicos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antecedentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificado_procuraduria', models.FileField(help_text='Procuraduría General de la Nación. Formatos: PDF, JPG, PNG. Máx: 10 MB', upload_to='antecedentes/procuraduria/', validators=[formapp.validators.validate_file_size, formapp.validators.validate_file_extension, formapp.validators.validate_file_mime], verbose_name='Certificado de Antecedentes Disciplinarios')),
                ('fecha_procuraduria', models.DateField(verbose_name='Fecha de Expedición Procuraduría')),
                ('certificado_contraloria', models.FileField(help_text='Contraloría General de la República. Formatos: PDF, JPG, PNG. Máx: 10 MB', upload_to='antecedentes/contraloria/', validators=[formapp.validators.validate_file_size, formapp.validators.validate_file_extension, formapp.validators.validate_file_mime], verbose_name='Certificado de Antecedentes Fiscales')),
                ('fecha_contraloria', models.DateField(verbose_name='Fecha de Expedición Contraloría')),
                ('certificado_policia', models.FileField(help_text='Policía Nacional de Colombia. Formatos: PDF, JPG, PNG. Máx: 10 MB', upload_to='antecedentes/policia/', validators=[formapp.validators.validate_file_size, formapp.validators.validate_file_extension, formapp.validators.validate_file_mime], verbose_name='Certificado de Antecedentes Judiciales')),
                ('fecha_policia', models.DateField(verbose_name='Fecha de Expedición Policía')),
                ('certificado_medidas_correctivas', models.FileField(help_text='RNMC - Policía Nacional. Formatos: PDF, JPG, PNG. Máx: 10 MB', upload_to='antecedentes/medidas_correctivas/', validators=[formapp.validators.validate_file_size, formapp.validators.validate_file_extension, formapp.validators.validate_file_mime], verbose_name='Registro de Medidas Correctivas')),
                ('fecha_medidas_correctivas', models.DateField(verbose_name='Fecha de Expedición RNMC')),
                ('certificado_delitos_sexuales', models.FileField(help_text='Ley 1918 de 2018. Formatos: PDF, JPG, PNG. Máx: 10 MB', upload_to='antecedentes/delitos_sexuales/', validators=[formapp.validators.validate_file_size, formapp.validators.validate_file_extension, formapp.validators.validate_file_mime], verbose_name='Consulta Inhabilidades Delitos Sexuales')),
                ('fecha_delitos_sexuales', models.DateField(verbose_name='Fecha de Consulta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('informacion_basica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes', to='formapp.informacionbasica')),
            ],
            options={
                'verbose_name': 'Antecedentes',
                'verbose_name_plural': 'Antecedentes',
            },
        ),
    ]
