# Generated by Django 5.2.7 on 2025-11-19 01:08

import django.db.models.deletion
import formapp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0016_antecedentes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexosAdicionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anexo_03_datos_personales', models.FileField(blank=True, help_text='Formato de datos personales vigente. Formatos: PDF, JPG, PNG. Máx: 10 MB', null=True, upload_to='anexos/anexo_03/', validators=[formapp.validators.validate_file_size, formapp.validators.validate_file_extension, formapp.validators.validate_file_mime], verbose_name='ANEXO 03 - Datos Personales')),
                ('carta_intencion', models.FileField(blank=True, help_text='Carta de intención firmada. Formatos: PDF, JPG, PNG. Máx: 10 MB', null=True, upload_to='anexos/cartas_intencion/', validators=[formapp.validators.validate_file_size, formapp.validators.validate_file_extension, formapp.validators.validate_file_mime], verbose_name='Carta de Intención o Contrato')),
                ('otros_documentos', models.FileField(blank=True, help_text='Documentos adicionales. Formatos: PDF, JPG, PNG. Máx: 10 MB', null=True, upload_to='anexos/otros/', validators=[formapp.validators.validate_file_size, formapp.validators.validate_file_extension, formapp.validators.validate_file_mime], verbose_name='Otros Documentos')),
                ('descripcion_otros', models.TextField(blank=True, null=True, verbose_name='Descripción de Otros Documentos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('informacion_basica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anexos_adicionales', to='formapp.informacionbasica')),
            ],
            options={
                'verbose_name': 'Anexos Adicionales',
                'verbose_name_plural': 'Anexos Adicionales',
            },
        ),
    ]
