# Generated by Django 5.2.7 on 2025-11-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0017_anexos_adicionales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentosidentidad',
            name='carta_autorizacion_datos',
        ),
        migrations.RemoveField(
            model_name='documentosidentidad',
            name='fecha_autorizacion',
        ),
        migrations.RemoveField(
            model_name='especializacion',
            name='meses_de_experiencia',
        ),
        migrations.RemoveField(
            model_name='informacionacademica',
            name='meses_experiencia_profesion',
        ),
        migrations.RemoveField(
            model_name='posgrado',
            name='meses_de_experiencia',
        ),
        migrations.AlterField(
            model_name='calculoexperiencia',
            name='anos_y_meses_experiencia',
            field=models.CharField(max_length=200, verbose_name='Años y Meses de Experiencia'),
        ),
        migrations.AlterField(
            model_name='documentosidentidad',
            name='distrito_militar',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Distrito Militar'),
        ),
        migrations.AlterField(
            model_name='informacionacademica',
            name='numero_tarjeta_resolucion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='N° Tarjeta o Resolución'),
        ),
        migrations.AlterField(
            model_name='informacionacademica',
            name='tarjeta_profesional',
            field=models.CharField(choices=[('Tarjeta Profesional', 'Tarjeta Profesional'), ('Resolución', 'Resolución'), ('No Aplica', 'No Aplica')], default='No Aplica', max_length=200, verbose_name='Tarjeta o Resolución Profesional'),
        ),
        migrations.AlterField(
            model_name='informacionbasica',
            name='barrio',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Barrio'),
        ),
        migrations.AlterField(
            model_name='informacionbasica',
            name='complemento_direccion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Complemento (Apto, Interior, etc.)'),
        ),
    ]
