# Generated by Django 5.2.7 on 2025-11-19 14:13

import formapp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0018_remove_documentosidentidad_carta_autorizacion_datos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexosadicionales',
            name='anexo_03_datos_personales',
            field=models.FileField(blank=True, help_text='Formato de datos personales vigente. Formatos: PDF, JPG, PNG. Máx: 10 MB', max_length=200, null=True, upload_to='anexos/anexo_03/', validators=[formapp.validators.validate_file_size, formapp.validators.validate_file_extension, formapp.validators.validate_file_mime], verbose_name='ANEXO 03 - Datos Personales'),
        ),
        migrations.AlterField(
            model_name='anexosadicionales',
            name='carta_intencion',
            field=models.FileField(blank=True, help_text='Carta de intención firmada. Formatos: PDF, JPG, PNG. Máx: 10 MB', max_length=200, null=True, upload_to='anexos/cartas_intencion/', validators=[formapp.validators.validate_file_size, formapp.validators.validate_file_extension, formapp.validators.validate_file_mime], verbose_name='Carta de Intención o Contrato'),
        ),
        migrations.AlterField(
            model_name='anexosadicionales',
            name='otros_documentos',
            field=models.FileField(blank=True, help_text='Documentos adicionales. Formatos: PDF, JPG, PNG. Máx: 10 MB', max_length=200, null=True, upload_to='anexos/otros/', validators=[formapp.validators.validate_file_size, formapp.validators.validate_file_extension, formapp.validators.validate_file_mime], verbose_name='Otros Documentos'),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='certificado_contraloria',
            field=models.FileField(help_text='Contraloría General de la República. Formatos: PDF, JPG, PNG. Máx: 10 MB', max_length=200, upload_to='antecedentes/contraloria/', validators=[formapp.validators.validate_file_size, formapp.validators.validate_file_extension, formapp.validators.validate_file_mime], verbose_name='Certificado de Antecedentes Fiscales'),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='certificado_delitos_sexuales',
            field=models.FileField(help_text='Ley 1918 de 2018. Formatos: PDF, JPG, PNG. Máx: 10 MB', max_length=200, upload_to='antecedentes/delitos_sexuales/', validators=[formapp.validators.validate_file_size, formapp.validators.validate_file_extension, formapp.validators.validate_file_mime], verbose_name='Consulta Inhabilidades Delitos Sexuales'),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='certificado_medidas_correctivas',
            field=models.FileField(help_text='RNMC - Policía Nacional. Formatos: PDF, JPG, PNG. Máx: 10 MB', max_length=200, upload_to='antecedentes/medidas_correctivas/', validators=[formapp.validators.validate_file_size, formapp.validators.validate_file_extension, formapp.validators.validate_file_mime], verbose_name='Registro de Medidas Correctivas'),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='certificado_policia',
            field=models.FileField(help_text='Policía Nacional de Colombia. Formatos: PDF, JPG, PNG. Máx: 10 MB', max_length=200, upload_to='antecedentes/policia/', validators=[formapp.validators.validate_file_size, formapp.validators.validate_file_extension, formapp.validators.validate_file_mime], verbose_name='Certificado de Antecedentes Judiciales'),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='certificado_procuraduria',
            field=models.FileField(help_text='Procuraduría General de la Nación. Formatos: PDF, JPG, PNG. Máx: 10 MB', max_length=200, upload_to='antecedentes/procuraduria/', validators=[formapp.validators.validate_file_size, formapp.validators.validate_file_extension, formapp.validators.validate_file_mime], verbose_name='Certificado de Antecedentes Disciplinarios'),
        ),
        migrations.AlterField(
            model_name='documentosidentidad',
            name='fotocopia_cedula',
            field=models.FileField(help_text='Formatos permitidos: PDF, JPG, PNG. Tamaño máximo: 10 MB', max_length=200, upload_to='documentos_identidad/cedulas/', validators=[formapp.validators.validate_file_size, formapp.validators.validate_file_extension, formapp.validators.validate_file_mime], verbose_name='Fotocopia Cédula de Ciudadanía'),
        ),
        migrations.AlterField(
            model_name='documentosidentidad',
            name='libreta_militar',
            field=models.FileField(blank=True, help_text='Opcional. Formatos: PDF, JPG, PNG. Máx: 10 MB', max_length=200, null=True, upload_to='documentos_identidad/libretas_militares/', validators=[formapp.validators.validate_file_size, formapp.validators.validate_file_extension, formapp.validators.validate_file_mime], verbose_name='Libreta Militar'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='certificado_laboral',
            field=models.FileField(help_text='Formatos permitidos: PDF, JPG, PNG. Tamaño máximo: 10 MB', max_length=200, upload_to='certificados_laborales/', validators=[formapp.validators.validate_file_size, formapp.validators.validate_file_extension, formapp.validators.validate_file_mime], verbose_name='Certificado Laboral o Contractual'),
        ),
        migrations.AlterField(
            model_name='informacionacademica',
            name='certificado_vigencia_tarjeta',
            field=models.FileField(blank=True, help_text='Certificado de vigencia de tarjeta profesional. Formatos: PDF, JPG, PNG. Máx: 10 MB', max_length=200, null=True, upload_to='certificados_vigencia/', validators=[formapp.validators.validate_file_size, formapp.validators.validate_file_extension, formapp.validators.validate_file_mime], verbose_name='Certificado de Vigencia'),
        ),
        migrations.AlterField(
            model_name='informacionacademica',
            name='fotocopia_tarjeta_profesional',
            field=models.FileField(blank=True, help_text='Solo si aplica. Formatos: PDF, JPG, PNG. Máx: 10 MB', max_length=200, null=True, upload_to='tarjetas_profesionales/', validators=[formapp.validators.validate_file_size, formapp.validators.validate_file_extension, formapp.validators.validate_file_mime], verbose_name='Fotocopia Tarjeta Profesional'),
        ),
        migrations.AlterField(
            model_name='informacionacademica',
            name='fotocopia_titulo',
            field=models.FileField(blank=True, help_text='Acta de grado o diploma. Formatos: PDF, JPG, PNG. Máx: 10 MB', max_length=200, null=True, upload_to='titulos_academicos/', validators=[formapp.validators.validate_file_size, formapp.validators.validate_file_extension, formapp.validators.validate_file_mime], verbose_name='Fotocopia del Título/Diploma'),
        ),
    ]
