# Generated by Django 5.2.7 on 2025-11-19 18:07

import formapp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0019_alter_anexosadicionales_anexo_03_datos_personales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentosidentidad',
            name='hoja_de_vida',
            field=models.FileField(blank=True, help_text='Formatos permitidos: PDF, JPG, PNG. Tamaño máximo: 10 MB', max_length=200, null=True, upload_to='documentos_identidad/hojas_de_vida/', validators=[formapp.validators.validate_file_size, formapp.validators.validate_file_extension, formapp.validators.validate_file_mime], verbose_name='Hoja de Vida'),
        ),
    ]
