# Generated by Django 5.2.7 on 2025-11-19 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0020_add_hoja_de_vida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informacionbasica',
            name='area_conocimiento',
        ),
        migrations.RemoveField(
            model_name='informacionbasica',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='informacionbasica',
            name='experiencia',
        ),
        migrations.RemoveField(
            model_name='informacionbasica',
            name='organizacion',
        ),
        migrations.RemoveField(
            model_name='informacionbasica',
            name='tiempo_experiencia',
        ),
        migrations.RemoveField(
            model_name='informacionbasica',
            name='tipo_perfil',
        ),
    ]
