# Generated by Django 5.2.7 on 2025-11-19 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0021_remove_admin_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacionbasica',
            name='area_del_conocimiento_otro',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Área del Conocimiento (Otro)'),
        ),
        migrations.AddField(
            model_name='informacionbasica',
            name='perfil_otro',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Perfil Profesional (Otro)'),
        ),
        migrations.AddField(
            model_name='informacionbasica',
            name='profesion_otro',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Profesión (Otro)'),
        ),
    ]
