# Generated by Django 5.2.7 on 2025-11-24 14:39

import formapp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0022_add_choices_and_otro_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentosidentidad',
            name='fotocopia_cedula',
            field=models.FileField(help_text='Se requiere al 150%. Formatos permitidos: PDF, JPG, PNG. Tamaño máximo: 10 MB', max_length=200, upload_to='documentos_identidad/cedulas/', validators=[formapp.validators.validate_file_size, formapp.validators.validate_file_extension, formapp.validators.validate_file_mime], verbose_name='Fotocopia Cédula de Ciudadanía'),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='funciones',
            field=models.TextField(verbose_name='Actividades Desarrolladas'),
        ),
        migrations.AlterField(
            model_name='informacionbasica',
            name='genero',
            field=models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino'), ('Otro', 'Otro')], max_length=50, verbose_name='Género'),
        ),
    ]
