# Generated by Django 5.2.7 on 2025-11-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0023_alter_documentosidentidad_fotocopia_cedula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacionbasica',
            name='primer_apellido',
            field=models.CharField(default='', max_length=50, verbose_name='Primer Apellido'),
        ),
        migrations.AddField(
            model_name='informacionbasica',
            name='primer_nombre',
            field=models.CharField(default='', max_length=50, verbose_name='Primer Nombre'),
        ),
        migrations.AddField(
            model_name='informacionbasica',
            name='segundo_apellido',
            field=models.CharField(default='', max_length=50, verbose_name='Segundo Apellido'),
        ),
        migrations.AddField(
            model_name='informacionbasica',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Segundo Nombre'),
        ),
    ]
