# Generated by Django 5.2.7 on 2025-11-24 17:36

import django.core.validators
import django.db.models.deletion
import formapp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0024_informacionbasica_primer_apellido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducacionBasica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.CharField(max_length=200, verbose_name='Institución Educativa')),
                ('anio_grado', models.IntegerField(validators=[django.core.validators.MinValueValidator(1950)], verbose_name='Año de Grado')),
                ('titulo', models.CharField(default='Bachiller Académico', max_length=200, verbose_name='Título Obtenido')),
                ('acta_grado_diploma', models.FileField(blank=True, help_text='Formatos: PDF, JPG, PNG. Máx: 10 MB', max_length=200, null=True, upload_to='educacion_basica/', validators=[formapp.validators.validate_file_size, formapp.validators.validate_file_extension, formapp.validators.validate_file_mime], verbose_name='Acta de Grado o Diploma')),
                ('informacion_basica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educacion_basica', to='formapp.informacionbasica')),
            ],
        ),
        migrations.CreateModel(
            name='EducacionSuperior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('Tecnico', 'Técnico'), ('Tecnologo', 'Tecnólogo')], max_length=20, verbose_name='Nivel de Formación')),
                ('institucion', models.CharField(max_length=200, verbose_name='Institución Educativa')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título Obtenido')),
                ('fecha_grado', models.DateField(verbose_name='Fecha de Grado')),
                ('tarjeta_profesional', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tarjeta Profesional (Opcional)')),
                ('documento_soporte', models.FileField(blank=True, help_text='Formatos: PDF, JPG, PNG. Máx: 10 MB', max_length=200, null=True, upload_to='educacion_superior/', validators=[formapp.validators.validate_file_size, formapp.validators.validate_file_extension, formapp.validators.validate_file_mime], verbose_name='Diploma o Acta de Grado')),
                ('informacion_basica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educacion_superior', to='formapp.informacionbasica')),
            ],
        ),
    ]
