# Generated by Django 5.2.7 on 2025-11-24 19:22

import formapp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0025_educacionbasica_educacionsuperior'),
    ]

    operations = [
        migrations.AddField(
            model_name='especializacion',
            name='acta_grado_diploma',
            field=models.FileField(blank=True, help_text='Formatos: PDF, JPG, PNG. Máx: 10 MB', max_length=200, null=True, upload_to='especializaciones/', validators=[formapp.validators.validate_file_size, formapp.validators.validate_file_extension, formapp.validators.validate_file_mime], verbose_name='Acta de Grado o Diploma'),
        ),
        migrations.AddField(
            model_name='informacionbasica',
            name='acepta_politica',
            field=models.BooleanField(default=False, help_text='Debe aceptar la política de tratamiento de datos para continuar.', verbose_name='Acepto política de tratamiento de datos'),
        ),
        migrations.AddField(
            model_name='posgrado',
            name='acta_grado_diploma',
            field=models.FileField(blank=True, help_text='Formatos: PDF, JPG, PNG. Máx: 10 MB', max_length=200, null=True, upload_to='posgrados/', validators=[formapp.validators.validate_file_size, formapp.validators.validate_file_extension, formapp.validators.validate_file_mime], verbose_name='Acta de Grado o Diploma'),
        ),
    ]
