# Generated by Django 5.2.7 on 2025-11-25 16:26

import formapp.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0026_especializacion_acta_grado_diploma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacionbasica',
            name='estado',
            field=models.CharField(choices=[('RECIBIDO', 'Recibido'), ('EN_REVISION', 'En Revisión'), ('PENDIENTE_CORRECCION', 'Pendiente de Corrección'), ('CORREGIDO', 'Corregido por Candidato'), ('VERIFICADO', 'Verificado / Aprobado'), ('RECHAZADO', 'Rechazado')], default='RECIBIDO', max_length=50, verbose_name='Estado del Proceso'),
        ),
        migrations.AddField(
            model_name='informacionbasica',
            name='token_correccion',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='informacionbasica',
            name='token_expiracion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiración del Token'),
        ),
        migrations.AlterField(
            model_name='documentosidentidad',
            name='fotocopia_cedula',
            field=models.FileField(help_text='<strong style="color: #dc3545; font-size: 1.1em;">⚠️ IMPORTANTE: Se requiere al 150% (ampliada)</strong><br>Formatos permitidos: PDF, JPG, PNG. Tamaño máximo: 10 MB', max_length=200, upload_to='documentos_identidad/cedulas/', validators=[formapp.validators.validate_file_size, formapp.validators.validate_file_extension, formapp.validators.validate_file_mime], verbose_name='Fotocopia Cédula de Ciudadanía'),
        ),
    ]
