# Generated by Django 5.2.7 on 2025-11-25 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0027_informacionbasica_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacionbasica',
            name='comentarios_correccion',
            field=models.TextField(blank=True, help_text='Explicación del candidato sobre qué información corrigió', null=True, verbose_name='Comentarios de Corrección del Candidato'),
        ),
        migrations.CreateModel(
            name='HistorialCorreccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('mensaje_admin', models.TextField(help_text='Observaciones enviadas al candidato', verbose_name='Mensaje del Administrador')),
                ('admin_usuario', models.CharField(help_text='Usuario que solicitó la corrección', max_length=150, verbose_name='Usuario Administrador')),
                ('fecha_correccion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Corrección')),
                ('comentarios_candidato', models.TextField(blank=True, help_text='Explicación del candidato sobre las correcciones realizadas', null=True, verbose_name='Comentarios del Candidato')),
                ('token_usado', models.UUIDField(blank=True, null=True, verbose_name='Token Utilizado')),
                ('informacion_basica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_correcciones', to='formapp.informacionbasica', verbose_name='Información Básica')),
            ],
            options={
                'verbose_name': 'Historial de Corrección',
                'verbose_name_plural': 'Historial de Correcciones',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
