# Generated by Django 5.2.7 on 2025-11-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0028_informacionbasica_comentarios_correccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialcorreccion',
            name='campos_a_corregir',
            field=models.JSONField(blank=True, default=list, help_text='Lista de nombres de campos que el candidato debe corregir', verbose_name='Campos a Corregir'),
        ),
        migrations.AddField(
            model_name='informacionbasica',
            name='campos_a_corregir',
            field=models.JSONField(blank=True, default=list, help_text='Lista de campos que el candidato debe corregir', verbose_name='Campos a Corregir'),
        ),
    ]
