# Generated by Django 5.2.7 on 2025-12-09 14:44

import formapp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0029_historialcorreccion_campos_a_corregir_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='antecedentes',
            name='certificado_redam',
            field=models.FileField(blank=True, help_text='Certificado REDAM. Formatos: PDF, JPG, PNG. Máx: 10 MB', max_length=200, null=True, upload_to='antecedentes/redam/', validators=[formapp.validators.validate_file_size, formapp.validators.validate_file_extension, formapp.validators.validate_file_mime], verbose_name='Consulta Registro de Deudores Alimentarios Morosos (REDAM)'),
        ),
        migrations.AddField(
            model_name='antecedentes',
            name='fecha_redam',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Consulta REDAM'),
        ),
    ]
