# Generated by Django 5.2.7 on 2026-03-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0033_educacionsuperior_tiene_tarjeta_profesional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educacionsuperior',
            name='tarjeta_profesional',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='N° Tarjeta Profesional'),
        ),
    ]
