# Generated by Django 5.2.7 on 2025-12-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsolidadoBaseDatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100, verbose_name='Área')),
                ('tipo_documento', models.CharField(max_length=100, verbose_name='Tipo de Documento')),
                ('numero_contrato_otrosi', models.CharField(max_length=100, verbose_name='No. de Contrato / Otrosí')),
                ('nombre_contratista', models.CharField(max_length=200, verbose_name='Nombre del Contratista')),
                ('cedula', models.BigIntegerField(db_index=True, verbose_name='Cédula del Contratista')),
                ('contratante_nit', models.CharField(max_length=300, verbose_name='Contratante (NIT)')),
                ('objeto_contrato', models.TextField(verbose_name='Objeto del Contrato')),
                ('fecha_firma', models.DateField(verbose_name='Fecha de Firma')),
                ('fecha_final', models.DateField(verbose_name='Plazo de Duración (Fecha Final)')),
                ('actividades_especificas', models.TextField(blank=True, null=True, verbose_name='Actividades Específicas / Modificación')),
                ('estado', models.CharField(max_length=50, verbose_name='ESTADO')),
            ],
            options={
                'verbose_name': 'Consolidado Base de Datos',
                'verbose_name_plural': 'Consolidados Base de Datos',
            },
        ),
        migrations.CreateModel(
            name='ContratoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.BigIntegerField(db_index=True, verbose_name='Cédula')),
                ('nombre_contratista', models.CharField(max_length=200, verbose_name='Nombre Contratista')),
                ('numero_registro', models.IntegerField(verbose_name='N°')),
                ('contrato', models.CharField(max_length=100, verbose_name='Contrato')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha Fin')),
                ('dias_brutos', models.IntegerField(verbose_name='Días Brutos')),
                ('traslape', models.CharField(max_length=10, verbose_name='¿Traslape/Unión?')),
                ('explicacion_detallada', models.TextField(blank=True, null=True, verbose_name='Explicación Detallada')),
                ('dias_reales_contribuidos', models.IntegerField(verbose_name='Días Reales Contribuidos')),
            ],
            options={
                'verbose_name': 'Contrato Histórico',
                'verbose_name_plural': 'Historial de Contratos (Detalle)',
                'ordering': ['cedula', 'fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ExperienciaTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.BigIntegerField(db_index=True, verbose_name='Cédula del Contratista')),
                ('nombre_contratista', models.CharField(max_length=200, verbose_name='Nombre del Contratista')),
                ('experiencia_bruta_dias', models.IntegerField(verbose_name='Experiencia Bruta (Días - Con Traslape)')),
                ('experiencia_neta_dias', models.IntegerField(verbose_name='Experiencia Neta (Días - Sin Superposición)')),
                ('experiencia_neta_texto', models.CharField(max_length=100, verbose_name='Experiencia Neta (Años, Meses, Días)')),
            ],
            options={
                'verbose_name': 'Experiencia Total Acumulada',
                'verbose_name_plural': 'Experiencias Totales Acumuladas',
            },
        ),
        migrations.CreateModel(
            name='PersonalUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carpeta_general', models.CharField(default='CONTRATOS PERSONAL 2025-2017', max_length=50, verbose_name='Carpeta General')),
                ('area', models.CharField(max_length=100, verbose_name='Área (Nivel 1)')),
                ('contratista', models.CharField(max_length=200, verbose_name='Contratista (Nivel 2)')),
                ('enlace_carpeta', models.URLField(max_length=500, verbose_name='Enlace Carpeta Contratista')),
                ('cedula', models.BigIntegerField(db_index=True, verbose_name='Cédula')),
            ],
            options={
                'verbose_name': 'URL Carpeta Personal',
                'verbose_name_plural': 'URLs Carpetas Personales',
            },
        ),
    ]
